"""
Django settings for vidhya_setu project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path

# --------------------
# BASE DIR
# --------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------
# SECURITY
# --------------------
SECRET_KEY = 'django-insecure-g&_#8^g==hmwhj3&)1pjlas@sm2*7if01$c1!n$-1rf%8!7cn6'

DEBUG = True

ALLOWED_HOSTS = []


# --------------------
# APPLICATIONS
# --------------------
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'accounts.apps.AccountsConfig',
    'attendance',
    'fees',
    'marks',
]


# --------------------
# MIDDLEWARE
# --------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # CSRF protection (IMPORTANT)
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]


# --------------------
# URL CONFIG
# --------------------
ROOT_URLCONF = 'vidhya_setu.urls'


# --------------------
# TEMPLATES
# --------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Global templates folder
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # login_required ke liye MUST
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --------------------
# WSGI
# --------------------
WSGI_APPLICATION = 'vidhya_setu.wsgi.application'


# --------------------
# DATABASE
# --------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --------------------
# PASSWORD VALIDATION
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------
# INTERNATIONALIZATION
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------
# STATIC FILES
# --------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# --------------------
# DEFAULT PRIMARY KEY
# --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------
# CUSTOM USER MODEL
# --------------------
AUTH_USER_MODEL = 'accounts.User'


# --------------------
# AUTH / LOGIN SETTINGS  🔥🔥 MOST IMPORTANT 🔥🔥
# --------------------
LOGIN_URL = '/login/'            # accounts/login/ bug FIX
LOGIN_REDIRECT_URL = '/'         # login ke baad
LOGOUT_REDIRECT_URL = '/login/'  # logout ke baad
