# Generated by Django 5.2.4 on 2025-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_homework_options_alter_homework_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_class', 'section', 'roll_no']},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SENIOR', 'Senior Teacher'), ('ASSISTANT', 'Assistant Teacher')], default=('1', 'Class 1'), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.PositiveIntegerField(help_text='Roll number within the class'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('student_class', 'section', 'roll_no')},
        ),
    ]
