# Generated by Django 5.2.4 on 2025-12-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentprofile_roll_no_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(default='0000000000', help_text='Parent contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(default='NA', help_text="Father's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.PositiveIntegerField(help_text='Roll number within the class'),
        ),
    ]
