# Generated by Django 5.2.4 on 2025-12-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_studentprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_class', 'section', 'roll_no'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
    ]
