# Generated by Django 5.2.4 on 2025-12-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.PositiveIntegerField(help_text='Auto-generated roll number (class & section wise)'),
        ),
    ]
