# Generated by Django 5.2.4 on 2025-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_class', 'section', 'roll_no']},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
