# Generated by Django 5.2.4 on 2026-01-02 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['student', 'subject']},
        ),
        migrations.AddField(
            model_name='studentmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='marks_obtained',
            field=models.PositiveIntegerField(help_text='Marks obtained by student'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='max_marks',
            field=models.PositiveIntegerField(help_text='Total marks of the exam (e.g. 70, 80, 100)'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='marks.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
