# Generated by Django 5.2.4 on 2026-01-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_studentmark_options_studentmark_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['student__username', 'subject__name']},
        ),
    ]
