# Generated by Django 5.2.4 on 2026-01-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_studentmark_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='uploaded_by',
        ),
    ]
