# Generated by Django 5.2.4 on 2026-01-04 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_alter_studentmark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['student__username', 'subject__name'], 'verbose_name': 'Student Mark', 'verbose_name_plural': 'Student Marks'},
        ),
        migrations.AddField(
            model_name='studentmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'subject')},
        ),
    ]
