# Generated by Django 5.2.4 on 2026-01-05 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_alter_studentmark_options_studentmark_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='exam_name',
            field=models.CharField(default='Unit Test', help_text='Eg: Unit Test, Mid Term, Final', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.CharField(default=1, help_text='Class for which subject belongs (e.g. 6, 7, 8)', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'subject', 'exam_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_name')},
        ),
    ]
