# Generated by Django 5.2.4 on 2026-01-02 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_attendance__student_76a8d7_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
